from __future__ import annotations

import random
from datetime import datetime, timedelta

from ..agents.utils.research_types import FundamentalSnapshot, NewsItem, PriceBar
from ..symbols import SymbolCandidate
from .stockstats_utils import render_indicator_report
from .utils import weekday_series


_FIXTURES = {
    "AAPL": {
        "name": "Apple Inc.",
        "exchange": "NASDAQ",
        "region": "US",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Consumer Electronics",
        "description": "A platform business spanning hardware, services, and ecosystem monetization.",
        "market_cap": 3100000000000,
        "trailing_pe": 31.4,
        "forward_pe": 28.8,
        "price_to_book": 42.0,
        "revenue_growth": 0.05,
        "gross_margin": 0.45,
        "operating_margin": 0.30,
        "debt_to_equity": 1.55,
        "current_ratio": 1.04,
        "free_cashflow": 101000000000,
        "base_price": 196.0,
        "trend_bias": 0.12,
        "volatility": 0.015,
        "volume": 62000000,
        "news": [
            ("Services revenue continues to offset slower device cycles", 0.45),
            ("Supplier checks point to steady premium phone demand", 0.30),
            ("Antitrust scrutiny remains an overhang for platform economics", -0.25),
        ],
    },
    "NVDA": {
        "name": "NVIDIA Corporation",
        "exchange": "NASDAQ",
        "region": "US",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Semiconductors",
        "description": "A compute platform company centered on accelerated AI infrastructure.",
        "market_cap": 3500000000000,
        "trailing_pe": 57.0,
        "forward_pe": 39.0,
        "price_to_book": 46.5,
        "revenue_growth": 0.84,
        "gross_margin": 0.76,
        "operating_margin": 0.59,
        "debt_to_equity": 0.24,
        "current_ratio": 3.4,
        "free_cashflow": 67000000000,
        "base_price": 1220.0,
        "trend_bias": 0.28,
        "volatility": 0.028,
        "volume": 52000000,
        "news": [
            ("Cloud demand keeps AI accelerator backlog elevated", 0.60),
            ("Hyperscaler capex plans reinforce next-year revenue visibility", 0.55),
            ("Valuation debate intensifies after sharp momentum rally", -0.10),
        ],
    },
    "MSFT": {
        "name": "Microsoft Corporation",
        "exchange": "NASDAQ",
        "region": "US",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Software Infrastructure",
        "description": "Enterprise platform business combining cloud, productivity, and AI distribution.",
        "market_cap": 3400000000000,
        "trailing_pe": 36.5,
        "forward_pe": 32.1,
        "price_to_book": 12.7,
        "revenue_growth": 0.16,
        "gross_margin": 0.69,
        "operating_margin": 0.45,
        "debt_to_equity": 0.36,
        "current_ratio": 1.32,
        "free_cashflow": 74000000000,
        "base_price": 441.0,
        "trend_bias": 0.14,
        "volatility": 0.014,
        "volume": 24000000,
        "news": [
            ("Azure demand remains solid as enterprise AI workloads expand", 0.42),
            ("Software seat growth supports recurring revenue resilience", 0.35),
            ("Cloud competition keeps pricing discipline in focus", -0.12),
        ],
    },
    "TSLA": {
        "name": "Tesla, Inc.",
        "exchange": "NASDAQ",
        "region": "US",
        "currency": "USD",
        "sector": "Consumer Cyclical",
        "industry": "Auto Manufacturers",
        "description": "Electric vehicle and energy platform business with a high-volatility retail following.",
        "market_cap": 650000000000,
        "trailing_pe": 62.0,
        "forward_pe": 49.0,
        "price_to_book": 10.4,
        "revenue_growth": 0.02,
        "gross_margin": 0.18,
        "operating_margin": 0.09,
        "debt_to_equity": 0.18,
        "current_ratio": 1.65,
        "free_cashflow": 5200000000,
        "base_price": 193.0,
        "trend_bias": -0.05,
        "volatility": 0.032,
        "volume": 96000000,
        "news": [
            ("Vehicle pricing pressure continues to squeeze margins", -0.48),
            ("Autonomy roadmap keeps long-duration optionality alive", 0.26),
            ("Delivery pace remains a battleground for the next quarter", -0.22),
        ],
    },
}


def _lookup(symbol: str) -> dict:
    upper = symbol.upper()
    if upper in _FIXTURES:
        return _FIXTURES[upper]
    return {
        "name": upper,
        "exchange": "NYSE",
        "region": "US",
        "currency": "USD",
        "sector": "Unknown",
        "industry": "Unknown",
        "description": "Synthetic placeholder profile generated by the offline dataflow.",
        "market_cap": 15000000000,
        "trailing_pe": 18.0,
        "forward_pe": 16.0,
        "price_to_book": 2.6,
        "revenue_growth": 0.03,
        "gross_margin": 0.31,
        "operating_margin": 0.14,
        "debt_to_equity": 0.65,
        "current_ratio": 1.42,
        "free_cashflow": 800000000,
        "base_price": 78.0,
        "trend_bias": 0.04,
        "volatility": 0.017,
        "volume": 4200000,
        "news": [
            ("Management keeps guidance steady as demand trends normalize", 0.12),
            ("Cost discipline offsets slower top-line momentum", 0.08),
            ("Investors await a clearer catalyst for multiple expansion", -0.05),
        ],
    }


def search_symbols(query: str, limit: int = 8) -> list[SymbolCandidate]:
    cleaned = " ".join(query.strip().split()).lower()
    if not cleaned:
        return []
    candidates: list[SymbolCandidate] = []
    for symbol, meta in _FIXTURES.items():
        if cleaned in symbol.lower() or cleaned in meta["name"].lower():
            candidates.append(
                SymbolCandidate(
                    symbol=symbol,
                    name=meta["name"],
                    exchange=meta["exchange"],
                    region=meta["region"],
                    currency=meta["currency"],
                    instrument_type="Equity",
                    provider="offline",
                    match_score=0.82 if cleaned != symbol.lower() else 0.99,
                )
            )
    if cleaned.upper() not in _FIXTURES and not candidates and cleaned.isalpha():
        symbol = cleaned.upper()
        meta = _lookup(symbol)
        candidates.append(
            SymbolCandidate(
                symbol=symbol,
                name=meta["name"],
                exchange=meta["exchange"],
                region=meta["region"],
                currency=meta["currency"],
                instrument_type="Equity",
                provider="offline",
                match_score=0.58,
            )
        )
    return candidates[:limit]


def get_price_history(symbol: str, analysis_date: str, lookback_days: int = 180) -> list[PriceBar]:
    meta = _lookup(symbol)
    anchor = datetime.strptime(analysis_date, "%Y-%m-%d").date()
    days = weekday_series(anchor, lookback_days)
    seed = sum(ord(ch) for ch in symbol.upper()) + int(anchor.strftime("%Y%m%d"))
    rng = random.Random(seed)
    close = float(meta["base_price"]) * (0.92 + rng.random() * 0.12)
    bars: list[PriceBar] = []
    for index, day in enumerate(days):
        drift = float(meta["trend_bias"]) / 252.0
        shock = rng.uniform(-float(meta["volatility"]), float(meta["volatility"]))
        close = max(2.0, close * (1.0 + drift + shock))
        open_price = max(1.0, close * (1.0 + rng.uniform(-0.007, 0.007)))
        high = max(open_price, close) * (1.0 + abs(rng.uniform(0.0, 0.015)))
        low = min(open_price, close) * (1.0 - abs(rng.uniform(0.0, 0.015)))
        volume = int(int(meta["volume"]) * (0.82 + rng.random() * 0.36))
        if index > len(days) - 15 and float(meta["trend_bias"]) > 0:
            close *= 1.002
        bars.append(
            PriceBar(
                date=day.isoformat(),
                open=round(open_price, 2),
                high=round(high, 2),
                low=round(low, 2),
                close=round(close, 2),
                volume=volume,
            )
        )
    return bars


def get_fundamentals(symbol: str) -> FundamentalSnapshot:
    meta = _lookup(symbol)
    return FundamentalSnapshot(
        company_name=meta["name"],
        sector=meta["sector"],
        industry=meta["industry"],
        description=meta["description"],
        market_cap=float(meta["market_cap"]),
        trailing_pe=float(meta["trailing_pe"]),
        forward_pe=float(meta["forward_pe"]),
        price_to_book=float(meta["price_to_book"]),
        revenue_growth=float(meta["revenue_growth"]),
        gross_margin=float(meta["gross_margin"]),
        operating_margin=float(meta["operating_margin"]),
        debt_to_equity=float(meta["debt_to_equity"]),
        current_ratio=float(meta["current_ratio"]),
        free_cashflow=float(meta["free_cashflow"]),
    )


def get_news(query: str, analysis_date: str, limit: int = 8) -> list[NewsItem]:
    symbol = query.upper().split()[0]
    meta = _lookup(symbol)
    anchor = datetime.strptime(analysis_date, "%Y-%m-%d").date()
    items: list[NewsItem] = []
    for index, (title, score) in enumerate(meta["news"][:limit]):
        published = anchor - timedelta(days=index * 3 + 1)
        items.append(
            NewsItem(
                title=title,
                source="Offline Desk",
                published_at=published.isoformat(),
                url="",
                summary=title,
                sentiment_score=score,
            )
        )
    return items


def get_global_news(analysis_date: str, theme: str = "macro", limit: int = 8) -> list[NewsItem]:
    headlines = [
        ("Rates and liquidity remain central to growth-stock leadership.", 0.05),
        ("AI capex continues to dominate enterprise and cloud spending debates.", 0.12),
        ("Broad market breadth and funding conditions remain the key macro cross-check.", -0.02),
    ]
    anchor = datetime.strptime(analysis_date, "%Y-%m-%d").date()
    items = []
    for index, (title, score) in enumerate(headlines[:limit]):
        items.append(
            NewsItem(
                title=f"{theme.title()}: {title}",
                source="Offline Macro Desk",
                published_at=(anchor - timedelta(days=index + 1)).isoformat(),
                summary=title,
                sentiment_score=score,
            )
        )
    return items


def get_indicators(symbol: str, analysis_date: str, indicators: list[str] | None = None) -> str:
    bars = get_price_history(symbol, analysis_date, 260)
    return render_indicator_report(bars, indicators)


def get_balance_sheet(symbol: str) -> str:
    meta = _lookup(symbol)
    return (
        f"Debt/Equity: {meta['debt_to_equity']}\nCurrent Ratio: {meta['current_ratio']}\n"
        f"Price/Book: {meta['price_to_book']}\nMarket Cap: {meta['market_cap']}"
    )


def get_cashflow(symbol: str) -> str:
    meta = _lookup(symbol)
    return (
        f"Free Cash Flow: {meta['free_cashflow']}\nOperating Margin: {meta['operating_margin']}\n"
        f"Revenue Growth: {meta['revenue_growth']}"
    )


def get_income_statement(symbol: str) -> str:
    meta = _lookup(symbol)
    return (
        f"Revenue Growth: {meta['revenue_growth']}\nGross Margin: {meta['gross_margin']}\n"
        f"Operating Margin: {meta['operating_margin']}\nTrailing PE: {meta['trailing_pe']}"
    )


def get_insider_transactions(symbol: str, analysis_date: str) -> str:
    meta = _lookup(symbol)
    if float(meta["revenue_growth"]) > 0.2:
        return "Recent insider activity does not obviously contradict the growth narrative; no large distress pattern is visible."
    return "Insider context is limited and does not provide a strong confirming signal."


def get_fundamental_documents(symbol: str, curr_date: str) -> list[dict]:
    from .fundamentals_rag import chunk_document_text

    meta = _lookup(symbol)
    sections = [
        (
            "10-K",
            f"{meta['name']} annual filing",
            (
                "Item 1 Business\n"
                f"{meta['description']} Revenue growth currently tracks {meta['revenue_growth']:.2f} with "
                f"gross margin near {meta['gross_margin']:.2f}. The business mix emphasizes durable customer demand, "
                "execution discipline, and competitive positioning.\n\n"
                "Item 7 Management Discussion and Analysis\n"
                f"Operating margin is near {meta['operating_margin']:.2f}, debt-to-equity is {meta['debt_to_equity']:.2f}, "
                f"and current ratio is {meta['current_ratio']:.2f}. Capital allocation remains anchored by free cash flow of "
                f"{meta['free_cashflow']:.0f} and management continues to frame guidance around backlog, demand visibility, and margins."
            ),
        ),
        (
            "earnings_call_transcript",
            f"{meta['name']} latest earnings call transcript",
            (
                "CEO: Demand trends remained resilient and management highlighted customer expansion, revenue visibility, "
                "and disciplined execution.\n"
                "CFO: Margin structure stayed healthy, capital allocation remained selective, and liquidity continued to "
                "support product investment and balance-sheet resilience."
            ),
        ),
    ]
    snippets: list[dict] = []
    for doc_type, title, text in sections:
        snippets.extend(
            chunk_document_text(
                text,
                title=title,
                doc_type=doc_type,
                filing_date=curr_date,
                provider="offline-fixtures",
                source=f"offline-fixtures:{symbol.upper()}:{doc_type}",
            )
        )
    return snippets


def validate_price_data(symbol: str, analysis_date: str) -> bool:
    try:
        return len(get_price_history(symbol, analysis_date, 90)) >= 20
    except Exception:
        return False


def validate_fundamental_data(symbol: str, analysis_date: str) -> bool:
    try:
        return bool(get_fundamentals(symbol).company_name)
    except Exception:
        return False
